PRJ_PATH = /home/trung97/Documents/ARM_Cotex_M4/prj/Hexapod_Robot/
BUILD_RESULT_DIR = Build_Result/
BUILD_RESULT_PATH = $(PRJ_PATH)$(BUILD_RESULT_DIR)
BUILD_RESULT_PATH_DRIVER = $(BUILD_RESULT_PATH)Driver/
BUILD_RESULT_PATH_HARDWARE_ABSTRACTION = $(BUILD_RESULT_PATH)Hardware_Abstraction/
BUILD_RESULT_PATH_APPLICATION = $(BUILD_RESULT_PATH)Application/